"""Protocols for the pipeline backends and loggers.

 pins TRL as the first concrete backend, but the abstractions
here are deliberately backend-agnostic so a CustomBackend can slot in for
an earlier experiment overhead-fairness comparisons.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, runtime_checkable

import numpy as np

# ---------------------------------------------------------------------------
# Data records - what gets persisted per training step.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class RolloutRecord:
    """One rollout/trajectory consumed by an optimization step.

        a full episode generated by the policy during RL fine-tuning,
        i.e. a sequence of (state, action, reward) with terminal reward;
        in LLM multi-turn settings a multi-turn interaction; in RLHF a
        prompt-generation pair scored by a reward model.
    """

    rollout_id: str
    step: int
    regime: str  # "ppo" / "grpo" / "dpo"
    prompt_hash: str
    response_hash: str
    reward: float
    advantage: float | None
    extra: dict


@dataclass(frozen=True)
class GradientEmbedding:
    """Low-rank gradient embedding for a rollout (TRAK/LoGra lineage)."""

    rollout_id: str
    step: int
    vector: np.ndarray  # shape (d,) where d = projected dim


@dataclass(frozen=True)
class CheckpointReference:
    """Pointer to a saved model checkpoint."""

    step: int
    path: Path
    metadata: dict


# ---------------------------------------------------------------------------
# Protocols.
# ---------------------------------------------------------------------------

@runtime_checkable
class RolloutLogger(Protocol):
    def log(self, record: RolloutRecord) -> None: ...
    def flush(self) -> None: ...


@runtime_checkable
class GradientEmbedder(Protocol):
    """Produces a fixed-dim embedding of a rollout's gradient.

    The projection is the cost-control lever for an earlier experiment (< 5% overhead) and
    the checkpoint-frequency lever.
    """

    @property
    def dim(self) -> int: ...

    def embed(self, rollout_id: str, step: int) -> GradientEmbedding: ...


@runtime_checkable
class CheckpointRegistry(Protocol):
    def register(self, ref: CheckpointReference) -> None: ...
    def list(self) -> list[CheckpointReference]: ...
    def latest(self) -> CheckpointReference | None: ...


@runtime_checkable
class ActivationExtractor(Protocol):
    """Extract a fixed-dim activation vector from a model for a given prompt.

    Used by an earlier experiment (Xiao & Aranguri activation-difference attribution) and by
    `behaviors.activation_diff_signature` (C2 signature for the cross-step
    estimator). The backend (HuggingFace model on Colab) implements this;
    locally we use a synthetic implementation for tests.

    The returned vector is a representation of the prompt at a specified
    layer (the layer choice is part of the extractor's configuration, not
    last-token activation at the configured layer, unless the implementation
    documents otherwise.
    """

    @property
    def dim(self) -> int: ...

    def extract(self, prompt: str) -> np.ndarray: ...

    def extract_batch(self, prompts: list[str]) -> np.ndarray:
        """Batched extraction; shape (N, dim). Implementations may fall back to
        per-prompt extraction if no batched path exists on the backend."""
        ...


@runtime_checkable
class Backend(Protocol):
    """Pluggable training backend.

    Implementations: `backends.trl_backend.TRLBackend`,
    `backends.custom_backend.CustomBackend` (reserved for an earlier experiment fairness).
    """

    regime: str  # "ppo" / "grpo" / "dpo"

    def attach(
        self,
        rollout_logger: RolloutLogger,
        gradient_embedder: GradientEmbedder,
        checkpoint_registry: CheckpointRegistry,
    ) -> None: ...

    def train(self) -> None: ...
